//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakiye_Kontrol.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banka()
        {
            this.Bakiye_Banka = new HashSet<Bakiye_Banka>();
            this.TAHSILAT_ODEME = new HashSet<TAHSILAT_ODEME>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BankaKodu { get; set; }
        public string BankaAdi { get; set; }
        public string SubeAdi { get; set; }
        public Nullable<int> HesapNo { get; set; }
        public string Iban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakiye_Banka> Bakiye_Banka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAHSILAT_ODEME> TAHSILAT_ODEME { get; set; }
    }
}
