//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakiye_Kontrol.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kasa()
        {
            this.Bakiye_Kasa = new HashSet<Bakiye_Kasa>();
            this.TAHSILAT_ODEME = new HashSet<TAHSILAT_ODEME>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KasaKodu { get; set; }
        public string KasaAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakiye_Kasa> Bakiye_Kasa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAHSILAT_ODEME> TAHSILAT_ODEME { get; set; }
    }
}
