//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakiye_Kontrol.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakiyeEntities : DbContext
    {
        public BakiyeEntities()
            : base("name=BakiyeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bakiye_Banka> Bakiye_Banka { get; set; }
        public virtual DbSet<Bakiye_Kasa> Bakiye_Kasa { get; set; }
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<TAHSILAT_ODEME> TAHSILAT_ODEME { get; set; }
        public virtual DbSet<Yeni_Hareket_Islem> Yeni_Hareket_Islem { get; set; }
    }
}
