//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakiye_Kontrol.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yeni_Hareket_Islem
    {
        public int ID { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<int> IslemNo { get; set; }
        public string Aciklama { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string OdemeAlan { get; set; }
    }
}
